#!/bin/bash
DATA_DIR="/home/njneetes/work/data/SALTAC/visit_1/tibia"

sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC001L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC001R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC002L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC002R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC004L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC004R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC005L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC005R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC006L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC006R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC007L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC007R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC008L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC008R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC010L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC010R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC013L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC013R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC014L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC014R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC015L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC015R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC018L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC018R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC019L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC019R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC020L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC020R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC021L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC021R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC023L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC023R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC025L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC025R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC027L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC027R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC030L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC030R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC032L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC032R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC033L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC033R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC034L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC034R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC036L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC036R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC037L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC037R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC038L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC038R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC039L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC039R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC040L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC040R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC041L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC041R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC045L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC045R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC047L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC047R_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC049L_T" slurm/inference/inference_unet.slurm; sleep 1
sbatch --export=DATA_DIR="$DATA_DIR",IMAGE="SLTC049R_T" slurm/inference/inference_unet.slurm; sleep 1