#!/bin/bash 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0001_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0001_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0001_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0001_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0002_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0002_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0002_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0002_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0002_FL V0S V03 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0002_TL V0S V03 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0002_FR V0S V03 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0002_TR V0S V03 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0003_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0003_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0003_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0003_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0004_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0004_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0004_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0004_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0005_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0005_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0005_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0005_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0006_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0006_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0006_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0006_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0007_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0007_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0007_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0007_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0008_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0008_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0008_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0008_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0009_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0009_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0009_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0009_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0010_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0010_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0010_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0010_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0011_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0011_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0011_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0011_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0012_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0012_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0012_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0012_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0013_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0013_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0013_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0013_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0014_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0014_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0014_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0014_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0015_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0015_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0015_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0015_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0016_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0016_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0016_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0016_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0017_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0017_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0017_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0017_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0018_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0018_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0018_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0018_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0019_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0019_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0019_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0019_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0020_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0020_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0020_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0020_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0021_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0021_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0021_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0021_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0022_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0022_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0022_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0022_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0023_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0023_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0023_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0023_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0024_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0024_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0024_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0024_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0024_FL V0S V03 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0024_TL V0S V03 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0024_FR V0S V03 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0024_TR V0S V03 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0025_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0025_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0025_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0025_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0026_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0026_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0026_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0026_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0027_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0027_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0027_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0027_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0028_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0028_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0028_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0028_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0029_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0029_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0029_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0029_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0030_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0030_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0030_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0030_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0031_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0031_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0031_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0031_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0032_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0032_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0032_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0032_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0033_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0033_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0033_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0033_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0034_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0034_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0034_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0034_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0035_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0035_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0035_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0035_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0036_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0036_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0036_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0036_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0037_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0037_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0037_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0037_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0038_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0038_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0038_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0038_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0039_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0039_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0039_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0039_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0040_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0040_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0040_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0040_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0041_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0041_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0041_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0041_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0042_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0042_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0042_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0042_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0043_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0043_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0043_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0043_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0044_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0044_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0044_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0044_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0045_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0045_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0045_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0045_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0046_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0046_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0046_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0046_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0047_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0047_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0047_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0047_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0048_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0048_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0048_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0048_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0049_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0049_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0049_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0049_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0050_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0050_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0050_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0050_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0051_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0051_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0051_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0051_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0052_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0052_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0052_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0052_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0053_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0053_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0053_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0053_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0054_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0054_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0054_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0054_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0055_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0055_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0055_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0055_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0056_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0056_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0056_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0056_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0057_FL V0S V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0057_TL V0S V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0057_FR V0S V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0057_TR V0S V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0058_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0058_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0058_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0058_TR V01 V02 tibia right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0059_FL V01 V02 femur left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0059_TL V01 V02 tibia left; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0059_FR V01 V02 femur right; sleep 0.1 
./projects/saltacii/shell/generate_rois_one_year.sh SLTCII0059_TR V01 V02 tibia right