#!/bin/bash
# this was needed because I forgot to also process the V0S scans originally in
# the segment_all_0_to_10_Feb-2-2024.sh script
./projects/saltacii/shell/segment_image.sh SLTCII0002_FL_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0002_TL_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0002_PL_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0002_FR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0002_TR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0002_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0003_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0003_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0003_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0003_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0003_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0003_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0004_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0004_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0004_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0004_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0004_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0004_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0005_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0005_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0005_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0005_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0005_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0005_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0006_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0006_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0006_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0006_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0006_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0006_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0007_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0007_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0007_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0007_FR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0007_TR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0007_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0008_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0008_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0008_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0008_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0008_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0008_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0009_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0009_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0009_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0009_FR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0009_TR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0009_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0010_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0010_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0010_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0010_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0010_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0010_PR_V0S no; sleep 0.1