#!/bin/bash 
./projects/saltacii/shell/segment_image.sh SLTCII0002_FL_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0002_TL_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0002_PL_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0002_FR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0002_TR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0002_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0003_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0003_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0003_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0003_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0003_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0003_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0004_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0004_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0004_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0004_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0004_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0004_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0005_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0005_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0005_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0005_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0005_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0005_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0006_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0006_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0006_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0006_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0006_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0006_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0007_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0007_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0007_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0007_FR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0007_TR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0007_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0008_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0008_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0008_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0008_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0008_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0008_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0009_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0009_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0009_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0009_FR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0009_TR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0009_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0010_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0010_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0010_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0010_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0010_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0010_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0011_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0011_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0011_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0011_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0011_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0011_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0012_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0012_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0012_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0012_FR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0012_TR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0012_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0013_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0013_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0013_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0013_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0013_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0013_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0014_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0014_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0014_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0014_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0014_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0014_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0015_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0015_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0015_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0015_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0015_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0015_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0016_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0016_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0016_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0016_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0016_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0016_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0017_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0017_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0017_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0017_FR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0017_TR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0017_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0018_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0018_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0018_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0018_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0018_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0018_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0019_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0019_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0019_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0019_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0019_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0019_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0020_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0020_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0020_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0020_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0020_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0020_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0021_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0021_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0021_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0021_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0021_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0021_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0022_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0022_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0022_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0022_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0022_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0022_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0023_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0023_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0023_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0023_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0023_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0023_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0024_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0024_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0024_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0024_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0024_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0024_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0025_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0025_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0025_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0025_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0025_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0025_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0026_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0026_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0026_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0026_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0026_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0026_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0027_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0027_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0027_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0027_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0027_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0027_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0028_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0028_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0028_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0028_FR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0028_TR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0028_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0029_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0029_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0029_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0029_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0029_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0029_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0030_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0030_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0030_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0030_FR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0030_TR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0030_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0031_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0031_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0031_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0031_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0031_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0031_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0032_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0032_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0032_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0032_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0032_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0032_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0033_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0033_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0033_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0033_FR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0033_TR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0033_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0034_FL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0034_TL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0034_PL_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0034_FR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0034_TR_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0034_PR_V0S no; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0035_FL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0035_TL_V0S yes; sleep 0.1
./projects/saltacii/shell/segment_image.sh SLTCII0035_PL_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0035_FR_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0035_TR_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0035_PR_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0037_FL_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0037_TL_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0037_PL_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0037_FR_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0037_TR_V0S no; sleep 0.1 
./projects/saltacii/shell/segment_image.sh SLTCII0037_PR_V0S no