#!/bin/bash
# medial reg
./projects/triknee/shell/treece.sh triknee_01_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_01_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_01_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_02_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_02_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_02_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_03_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_03_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_03_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_04_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_04_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_04_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_05_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_05_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_05_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_06_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_06_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_06_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_07_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_07_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_07_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_08_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_08_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_08_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_09_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_09_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_09_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_10_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_10_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_10_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_11_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_11_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_11_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_12_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_12_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_12_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_13_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_13_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_13_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_14_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_14_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_14_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_15_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_15_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_15_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_16_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_16_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_16_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_17_tr_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_17_tr_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_17_tr_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_18_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_18_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_18_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_19_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_19_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_19_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_20_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_20_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_20_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_21_tr_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_21_tr_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_21_tr_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_22_tr_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_22_tr_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_22_tr_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_23_tr_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_23_tr_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_23_tr_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_24_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_24_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_24_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_25_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_25_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_25_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_26_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_26_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_26_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_28_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_28_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_28_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_29_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_29_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_29_tl_3 medial reg 37
./projects/triknee/shell/treece.sh triknee_30_tl_1 medial reg 37
./projects/triknee/shell/treece.sh triknee_30_tl_2 medial reg 37
./projects/triknee/shell/treece.sh triknee_30_tl_3 medial reg 37
# lateral reg
./projects/triknee/shell/treece.sh triknee_01_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_01_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_01_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_02_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_02_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_02_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_03_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_03_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_03_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_04_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_04_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_04_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_05_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_05_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_05_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_06_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_06_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_06_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_07_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_07_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_07_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_08_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_08_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_08_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_09_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_09_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_09_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_10_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_10_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_10_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_11_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_11_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_11_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_12_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_12_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_12_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_13_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_13_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_13_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_14_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_14_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_14_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_15_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_15_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_15_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_16_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_16_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_16_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_17_tr_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_17_tr_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_17_tr_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_18_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_18_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_18_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_19_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_19_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_19_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_20_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_20_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_20_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_21_tr_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_21_tr_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_21_tr_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_22_tr_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_22_tr_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_22_tr_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_23_tr_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_23_tr_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_23_tr_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_24_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_24_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_24_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_25_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_25_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_25_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_26_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_26_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_26_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_28_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_28_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_28_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_29_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_29_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_29_tl_3 lateral reg 36
./projects/triknee/shell/treece.sh triknee_30_tl_1 lateral reg 36
./projects/triknee/shell/treece.sh triknee_30_tl_2 lateral reg 36
./projects/triknee/shell/treece.sh triknee_30_tl_3 lateral reg 36
# medial noreg
#./projects/triknee/shell/treece.sh triknee_01_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_01_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_01_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_02_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_02_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_02_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_03_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_03_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_03_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_04_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_04_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_04_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_05_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_05_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_05_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_06_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_06_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_06_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_07_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_07_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_07_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_08_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_08_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_08_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_09_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_09_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_09_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_10_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_10_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_10_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_11_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_11_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_11_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_12_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_12_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_12_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_13_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_13_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_13_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_14_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_14_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_14_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_15_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_15_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_15_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_16_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_16_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_16_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_17_tr_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_17_tr_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_17_tr_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_18_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_18_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_18_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_19_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_19_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_19_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_20_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_20_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_20_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_21_tr_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_21_tr_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_21_tr_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_22_tr_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_22_tr_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_22_tr_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_23_tr_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_23_tr_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_23_tr_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_24_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_24_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_24_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_25_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_25_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_25_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_26_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_26_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_26_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_28_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_28_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_28_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_29_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_29_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_29_tl_3 medial noreg 37
./projects/triknee/shell/treece.sh triknee_30_tl_1 medial noreg 37
./projects/triknee/shell/treece.sh triknee_30_tl_2 medial noreg 37
./projects/triknee/shell/treece.sh triknee_30_tl_3 medial noreg 37
# lateral noreg
./projects/triknee/shell/treece.sh triknee_01_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_01_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_01_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_02_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_02_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_02_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_03_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_03_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_03_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_04_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_04_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_04_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_05_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_05_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_05_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_06_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_06_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_06_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_07_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_07_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_07_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_08_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_08_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_08_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_09_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_09_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_09_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_10_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_10_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_10_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_11_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_11_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_11_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_12_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_12_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_12_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_13_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_13_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_13_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_14_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_14_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_14_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_15_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_15_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_15_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_16_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_16_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_16_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_17_tr_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_17_tr_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_17_tr_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_18_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_18_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_18_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_19_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_19_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_19_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_20_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_20_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_20_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_21_tr_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_21_tr_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_21_tr_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_22_tr_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_22_tr_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_22_tr_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_23_tr_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_23_tr_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_23_tr_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_24_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_24_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_24_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_25_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_25_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_25_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_26_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_26_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_26_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_28_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_28_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_28_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_29_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_29_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_29_tl_3 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_30_tl_1 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_30_tl_2 lateral noreg 36
./projects/triknee/shell/treece.sh triknee_30_tl_3 lateral noreg 36