#!/bin/bash
echo "femur.."
./projects/thor/shell/process_image.sh THOR337L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR337L_T1_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR253L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR560L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR560L_T1_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR240R_T0_F femur right; sleep 1
./projects/thor/shell/process_image.sh THOR177R_T0_F femur right; sleep 1
./projects/thor/shell/process_image.sh THOR177R_T1_F femur right; sleep 1
./projects/thor/shell/process_image.sh THOR242L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR242L_T1_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR464R_T0_F femur right; sleep 1
./projects/thor/shell/process_image.sh THOR320R_T0_F femur right; sleep 1
./projects/thor/shell/process_image.sh THOR121L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR471L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR474R_T0_F femur right; sleep 1
./projects/thor/shell/process_image.sh THOR227L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR227L_T1_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR139L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR410L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR473L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR186L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR207L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR583L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR171L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR498L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR592L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR543L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR125L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR359L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR420L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR115L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR317L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR350R_T0_F femur right; sleep 1
./projects/thor/shell/process_image.sh THOR154L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR554L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR188L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR349L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR526R_T0_F femur right; sleep 1
./projects/thor/shell/process_image.sh THOR406L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR260R_T0_F femur right; sleep 1
./projects/thor/shell/process_image.sh THOR265R_T0_F femur right; sleep 1
./projects/thor/shell/process_image.sh THOR168L_T0_F femur left; sleep 1
./projects/thor/shell/process_image.sh THOR165R_T0_F femur right; sleep 1
./projects/thor/shell/process_image.sh THOR276L_T0_F femur left; sleep 1
echo "tibia.."
./projects/thor/shell/process_image.sh THOR337L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR337L_T1_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR253L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR560L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR560L_T1_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR240R_T0_T tibia right; sleep 1
./projects/thor/shell/process_image.sh THOR177R_T0_T tibia right; sleep 1
./projects/thor/shell/process_image.sh THOR177R_T1_T tibia right; sleep 1
./projects/thor/shell/process_image.sh THOR242L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR242L_T1_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR464R_T0_T tibia right; sleep 1
./projects/thor/shell/process_image.sh THOR320R_T0_T tibia right; sleep 1
./projects/thor/shell/process_image.sh THOR121L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR471L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR474R_T0_T tibia right; sleep 1
./projects/thor/shell/process_image.sh THOR227L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR227L_T1_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR139L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR410L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR473L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR186L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR207L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR583L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR171L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR498L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR592L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR543L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR125L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR359L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR420L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR115L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR317L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR350R_T0_T tibia right; sleep 1
./projects/thor/shell/process_image.sh THOR154L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR554L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR188L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR349L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR526R_T0_T tibia right; sleep 1
./projects/thor/shell/process_image.sh THOR406L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR260R_T0_T tibia right; sleep 1
./projects/thor/shell/process_image.sh THOR265R_T0_T tibia right; sleep 1
./projects/thor/shell/process_image.sh THOR168L_T0_T tibia left; sleep 1
./projects/thor/shell/process_image.sh THOR165R_T0_T tibia right; sleep 1
./projects/thor/shell/process_image.sh THOR276L_T0_T tibia left; sleep 1