#!/bin/bash
./projects/triknee/shell/visualize.sh TRIKNEE_01_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_01_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_01_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_02_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_02_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_02_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_03_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_03_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_03_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_04_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_04_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_04_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_05_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_05_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_05_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_06_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_06_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_06_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_07_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_07_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_07_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_08_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_08_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_08_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_09_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_09_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_09_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_10_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_10_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_10_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_11_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_11_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_11_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_12_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_12_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_12_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_13_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_13_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_13_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_14_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_14_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_14_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_15_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_15_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_15_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_16_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_16_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_16_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_17_TR_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_17_TR_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_17_TR_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_18_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_18_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_18_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_19_TL_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_19_TL_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_19_TL_3; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_21_TR_1; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_21_TR_2; sleep 1
./projects/triknee/shell/visualize.sh TRIKNEE_21_TR_3; sleep 1