#!/bin/bash
./projects/conmed/shell/process_image.sh CONMD01R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD02R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD03R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD04R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD05R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD06R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD07R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD08R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD09R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD10R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD11R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD12R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD13R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD14R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD15R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD16R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD17R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD18R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD19R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD20R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD21R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD22R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD23R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD24R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD25R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD26R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD27R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD28R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD29R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD30R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD31R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD32R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD33R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD34R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD35R_T tibia right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD01R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD02R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD03R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD04R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD05R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD06R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD07R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD08R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD09R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD10R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD11R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD12R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD13R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD14R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD15R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD16R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD17R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD18R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD19R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD20R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD21R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD22R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD23R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD24R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD25R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD26R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD27R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD28R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD29R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD30R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD31R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD32R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD33R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD34R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD35R_F femur right; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD01L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD02L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD03L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD04L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD05L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD06L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD07L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD08L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD09L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD10L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD11L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD12L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD13L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD14L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD15L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD16L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD17L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD18L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD19L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD20L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD21L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD22L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD23L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD24L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD25L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD26L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD27L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD28L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD29L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD30L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD31L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD32L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD33L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD34L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD35L_T tibia left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD01L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD02L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD03L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD04L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD05L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD06L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD07L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD08L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD09L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD10L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD11L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD12L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD13L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD14L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD15L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD16L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD17L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD18L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD19L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD20L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD21L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD22L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD23L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD24L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD25L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD26L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD27L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD28L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD29L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD30L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD31L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD32L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD33L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD34L_F femur left; sleep 0.1
./projects/conmed/shell/process_image.sh CONMD35L_F femur left; sleep 0.1