#!/bin/bash
./projects/preoa/shell/process_image.sh PREOA_005_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_005_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_005_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_005_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_006_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_006_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_006_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_006_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_007_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_007_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_007_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_007_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_008_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_008_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_008_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_008_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_009_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_009_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_009_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_009_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_010_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_010_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_010_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_010_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_011_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_011_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_011_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_011_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_012_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_012_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_012_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_012_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_013_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_013_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_013_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_013_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_014_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_014_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_014_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_014_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_015_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_015_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_015_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_015_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_016_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_016_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_016_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_016_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_017_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_017_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_017_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_017_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_018_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_018_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_018_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_018_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_019_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_019_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_019_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_019_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_020_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_020_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_020_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_020_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_021_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_021_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_021_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_021_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_022_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_022_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_022_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_022_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_023_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_023_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_023_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_023_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_024_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_024_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_024_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_024_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_025_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_025_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_025_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_025_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_026_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_026_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_026_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_026_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_027_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_027_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_027_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_027_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_028_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_028_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_028_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_028_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_029_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_029_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_029_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_029_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_030_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_030_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_030_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_030_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_031_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_031_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_031_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_031_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_032_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_032_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_032_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_032_R_XCT_T tibia right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_033_L_XCT_F femur left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_033_L_XCT_T tibia left; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_033_R_XCT_F femur right; sleep 0.1
./projects/preoa/shell/process_image.sh PREOA_033_R_XCT_T tibia right; sleep 0.1